### PR TITLE
Setting max-width on imgs

### PR DESCRIPTION
**Pull request by noahmanger**
Preventing images from overflowing the container

### CODE REVIEW

**Comment by noahmanger** [comment]
Prevents this from happening:

screen shot 2015-07-30 at 10 21 13 am

**Comment by mbland** [comment]
Should this go in 18F/guides-template, and then imported via the template's `_scripts/copy-template` (explained in [the _Updating an existing guide_ section of the Guides Template intro](https://pages.18f.gov/guides-template/))?

**Comment by mbland** [comment]
Also, 18F/open-source-guide#5.

**Comment by mbland** [comment]
(Whoops, wrong issue for that last comment...)

**Comment by noahmanger** [comment]
Oh word. I didn't realize that was a thing. I just filed a separate PR into 18F/guides-template with the same fix

**Pull request merged**
